language: java
jdk:
 - openjdk8
sudo: required
services:
    - docker
env:
    global:
        - GIT_SHA=$(git rev-parse HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
before_install:
    - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
    - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash > /dev/null; fi
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file service-account.json
    - gcloud config set project graphite-maker-282419
    - gcloud config set compute/zone us-west1-a
    - gcloud container clusters get-credentials transportation-cluster
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
    skip_cleanup: true
    provider: script
    script: bash ./config/scripts/deploy.sh
    on:
        branch: master