version: '3'
services:
    psql-server:
        image: postgres
        container_name: psql-server
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=myuser
            - POSTGRES_PASSWORD=mypass
            - POSTGRES_DB=mydb
    jboss-server:
        build: .
        image: bananaforscale/transportation
        container_name: jboss-server
        ports:
            - "8080:8080"
            - "9990:9990"
        environment: 
            - DATASOURCE_SERVER=psql-server
            - DATASOURCE_DATABASE=mydb
            - DATASOURCE_USER=myuser
            - DATASOURCE_PASSWORD=mypass
