version: '3'
services:
    psql-server:
        image: postgres
        container_name: psql-server
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=myuser
            - POSTGRES_PASSWORD=mypass
            - POSTGRES_DB=mydb
    jboss-server:
        build: 
            context: ./service/transportation-service
            dockerfile: Dockerfile
        image: bananaforscale/transportation
        container_name: jboss-server
        ports:
            - "8080:8080"
            - "9990:9990"
        environment: 
            - DATASOURCE_HOST=psql-server
            - DATASOURCE_PORT=5432
            - DATASOURCE_DATABASE=mydb
            - DATASOURCE_USER=myuser
            - DATASOURCE_PASSWORD=mypass
