apiVersion: v1
kind: Pod
metadata:
    name: wildfly-pod
    labels:
        component: web
spec:
    containers:
        - name: wildfly
          image: jboss/wildfly
          ports:
              - containerPort: 8080
        
