apiVersion: apps/v1
kind: Deployment
metadata:
    name: wildfly-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: web
    template:
        metadata:
            labels:
                component: web
        spec:
            containers:
                - name: wildfly
                  image: jboss/wildfly
                  ports:
                      - containerPort: 8080
