apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: postgres-server
    template:
        metadata:
            labels:
                component: postgres-server
        spec:
            containers:
                - name: psql-server
                  image: postgres
                  ports:
                      - containerPort: 5432
